version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      elastic:
        aliases:
            - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      elastic:
        aliases:
            - elastic
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      elastic:
        aliases:
            - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    container_name: kibana
    depends_on:
      - es01
    networks:
      - elastic
    environment:
      SERVER_NAME: jankbana.org
      ELASTICSEARCH_HOSTS: http://elastic:9200
    ports:
      - 5601:5601

  logstash:
    build: ./logstash-img
    image: logstash-jk
    container_name: logstash
    networks:
      elastic:
        aliases:
            - logstash
    ports:
      - 9600:9600
      - 5044:5044
    volumes:
      - type: bind
        source: /home/goldman/log-bind
        target: /usr/share/logstash/arquivos-entrada

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
  logvolumestash:
    driver: local

networks:
  elastic:
    driver: bridge